FROM alpine:3.13 as builder

RUN set -eux \
	&& apk add --no-cache \
		bc \
		gcc \
		musl-dev \
		py3-pip \
		python3 \
		python3-dev

ARG MYPY_VERSION=latest
RUN set -eux \
	&& if [ "${MYPY_VERSION}" = "latest" ]; then \
		pip3 install --no-cache-dir --no-compile mypy; \
	else \
		pip3 install --no-cache-dir --no-compile "mypy>=${MYPY_VERSION},<$(echo "${MYPY_VERSION}+1" | bc)"; \
	fi \
	\
	&& mypy --version | grep -E '^mypy\s[0-9]+' \
	\
	&& find /usr/lib/ -name '__pycache__' -print0 | xargs -0 -n1 rm -rf \
	&& find /usr/lib/ -name '*.pyc' -print0 | xargs -0 -n1 rm -rf


FROM alpine:3.13 as production
# https://github.com/opencontainers/image-spec/blob/master/annotations.md
#LABEL "org.opencontainers.image.created"=""
#LABEL "org.opencontainers.image.version"=""
#LABEL "org.opencontainers.image.revision"=""
LABEL "maintainer"="cytopia <cytopia@everythingcli.org>"
LABEL "org.opencontainers.image.authors"="cytopia <cytopia@everythingcli.org>"
LABEL "org.opencontainers.image.vendor"="cytopia"
LABEL "org.opencontainers.image.licenses"="MIT"
LABEL "org.opencontainers.image.url"="https://github.com/cytopia/docker-mypy"
LABEL "org.opencontainers.image.documentation"="https://github.com/cytopia/docker-mypy"
LABEL "org.opencontainers.image.source"="https://github.com/cytopia/docker-mypy"
LABEL "org.opencontainers.image.ref.name"="mypy ${MYPY_VERSION}"
LABEL "org.opencontainers.image.title"="mypy ${MYPY_VERSION}"
LABEL "org.opencontainers.image.description"="mypy ${MYPY_VERSION}"

RUN set -eux \
	&& apk add --no-cache \
		python3 \
	&& ln -sf /usr/bin/python3 /usr/bin/python \
	&& find /usr/lib/ -name '__pycache__' -print0 | xargs -0 -n1 rm -rf \
	&& find /usr/lib/ -name '*.pyc' -print0 | xargs -0 -n1 rm -rf
COPY --from=builder /usr/lib/python3.8/site-packages/ /usr/lib/python3.8/site-packages/
COPY --from=builder /usr/bin/mypy /usr/bin/mypy
WORKDIR /data
ENTRYPOINT ["mypy"]
